services:
  postgres:
    image: postgres:16
    container_name: cms_postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: cms_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: cms_backend
    ports:
      - "5000:5000"
    environment:
      DATABASE_HOST: postgres
      DATABASE_PORT: 5432
      DATABASE_USER: postgres
      DATABASE_PASSWORD: postgres
      DATABASE_NAME: cms_db
    depends_on:
      - postgres
    volumes:
      - .:/usr/src/app
      - swagger_output:/usr/src/app/swagger

volumes:
  postgres_data:
  swagger_output:
    driver_opts:
      type: none
      o: bind
      device: ${PWD}/swagger
